name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Build
        run: |
          mkdir build
          cd build
          emcmake cmake -DSCORE_SECRET_KEY=${{ secrets.SCORE_SECRET_KEY }} ..
          emmake make

      - name: Setup public directory
        run: |
          mkdir -p public
          # cp build/f22_raptor.* public/
          cp build/public/* public/
          # cp -r assets public/
          cp index.html public/

          echo "/*" > public/_headers
          echo "  Cross-Origin-Embedder-Policy: require-corp" >> public/_headers
          echo "  Cross-Origin-Opener-Policy: same-origin" >> public/_headers
          echo "/*.data" >> public/_headers
          echo "  Content-Type: application/octet-stream" >> public/_headers

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public